### ISSUE TITLE
帐号登录正常，获取 download_url  总是出错啊

### ISSUE THREAD

**Issue by boyzhujian** [ly0/web.baidupan#3]
帐号登录正常，获取 download_url  总是出错啊

Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/root/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/root/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/root/.pyenv/versions/2.7.6/lib/python2.7/site-packages/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "/home/wwwroot/yundemo.1h9d.com/launcher.py", line 98, in GET
    return pcs.download_url(path)[0]
  File "/home/wwwroot/yundemo.1h9d.com/api.py", line 670, in download_url
    self.get_sign()
  File "/home/wwwroot/yundemo.1h9d.com/api.py", line 604, in get_sign
    sign1 = re.search(r'sign1 = \'(.+?)\';', html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by yuyuxp** [comment]
请问现在还能用吗？
